# Generated by Django 6.0 on 2026-06-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='about/')),
                ('background', models.TextField()),
                ('teamwork', models.TextField()),
                ('our_core_value', models.TextField()),
            ],
        ),
    ]
